version: "3.7"

services:
  tlstools:
    image: jsandas/tlstools
    build:
      context: .
    ports:
      - "8080:8080" 

  nginx:
    build:
      context: test_setup/conf/nginx
    image: jsandas/nginx
    ports:
      - "443:443"
    
  nginx_bad:
    build:
      context: test_setup/conf/nginx_bad
    image: jsandas/nginx_bad
    ports:
      - "8443:443"
    # volumes:
    #   - $PWD/test_setup/conf/nginx_bad/nginx.conf:/usr/local/nginx/conf/nginx.conf
  
  postfix_vuln:
    build:
      context: test_setup/conf/postfix
    image: jsandas/postfix_vuln
    ports:
      - "25:25"
      - "587:587"
    environment:
      - maildomain=mail.example.com
      - smtp_user=user:pwd

