name: run unit tests

on:
  pull_request:
    branches:
      - master

jobs:
  acceptance_testing:
    runs-on: ubuntu-latest
    name: Docker Build, Tag, Push
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build image
        run: docker-compose build -f acceptance.yml

      - name: Run acceptance tests
        run: ./run_acceptance_tests.py
