name: acceptance test

on:
  pull_request:
    branches:
      - master

jobs:
  acceptance_testing:
    runs-on: ubuntu-latest
    name: Acceptance
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Container Images
        run: docker-compose -f acceptance.yaml build

      - name: Run acceptance tests
        run: ./run_acceptance_tests.py
