name: tests

on:
  pull_request:
    branches:
      - master

jobs:
  acceptance_testing:
    runs-on: ubuntu-latest
    name: Acceptance
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run acceptance tests
        run: ./run_acceptance_tests.py
