name: build openssl docker image

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    name: Docker Build, Tag, Push
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build image
        run: docker build --tag ghcr.io/jsandas/tlstools/tlstools . 

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io/jsandas -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: docker push ghcr.io/jsandas/tlstools/tlstools


      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/jsandas/tlstools/tlstools
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          # Use Docker `latest` tag convention
          [ "$VERSION" == "master" ] && VERSION=latest
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          docker tag image $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION