name: integration tests

on:
  push:
    branches:
      - master

jobs:
  integration_testing:
    runs-on: ubuntu-latest
    name: Integrations
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run integration tests
        run: make integration stop
