name: release

on:
  push:
    tags:
      - '*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    name: Build, Tag, Push
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup env
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo "CHART_VERSION=$(cat chart/tlstools/Chart.yaml | grep version: | awk '{print $2}')" >> $GITHUB_ENV

      - name: Build image
        run: docker build --tag ghcr.io/jsandas/tlstools --tag ghcr.io/jsandas/tlstools:${{ env.RELEASE_VERSION }} . 

      - name: Push image
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io/jsandas -u ${{ github.actor }} --password-stdin
          docker push --all-tags ghcr.io/jsandas/tlstools
          docker logout ghcr.io/jsandas

      - name: Helm package
        run: helm package chart/tlstools --dependency-update --app-version=${{ env.RELEASE_VERSION }}

      - name: Helm push
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io/jsandas -u ${{ github.actor }} --password-stdin
          helm push tlstools-${{ env.CHART_VERSION }}.tgz oci://ghcr.io/jsandas
          docker logout ghcr.io/jsandas
