name: tests

on: [push]

jobs:
  unit-testing:
    runs-on: ubuntu-latest
    name: Unit
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build test image
        run: docker build -t test --target=build .

      - name: Run unit tests
        run: docker run test bash -c "./run_unit_tests.sh"
