name: unit test

on: [push]

jobs:
  unit-testing:
    runs-on: ubuntu-latest
    name: Unit
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run unit tests
        run: make unit_docker

      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.out
          flags: unittests
          name: codecov-umbrella
