name: unit test

on: [push]

jobs:
  unit-testing:
    runs-on: ubuntu-latest
    name: Unit
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build test image
        run: docker build -t test --target=build .

      - name: Run unit tests
        run: docker run -v $PWD:/go/src/tlstools test bash -c "./run_unit_tests.sh cov"

      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.out
